export const constants = {
    DOCUMENTS : 'Documents',
    NOVASOFT_IARPA_DATA: 'NovaSoft Iarpa Data',
    RASPBERRY_PI_SERVICE_BASE_URL : 'http://raspberrypi.local:8080/',
    LIST_FILES_PATH : 'listFiles',
    DOWNLOAD_FILE_PATH : 'downloadFile/',
    UPDATE_PARAM_PATH: 'updateParam',
    START_TEST_PATH: 'startTest',
    STOP_TEST_PATH: 'stopTest',
    PING_PATH: 'ping',
    FETCH_REAL_TIME_DATA_PATH: 'getRealTimeData',
    COMPREHENSIVE_UPDATE_PARAM_COMMAND: '!xu,',
    NON_COMPREHENSIVE_UPDATE_PARAM_COMMAND: '!au,',
    COMPREHENSIVE_START_TEST_COMMAND: '!xs,',
    NON_COMPREHENSIVE_START_TEST_COMMAND: '!as,',
    STOP_TEST_COMMAND: '!e,',
    NON_COMPREHENSIVE_PARAM_FILE_PATH: 'non_comprehensive_parameter.dat',
    COMPREHENSIVE_PARAM_FILE_PATH: 'comprehensive_parameter.dat',
    CONNECT_STATUS_CONNECTING: 'Connecting...',
    CONNECT_STATUS_CONNECTED: 'Connected',
    HTTP: 'Http',
    BLUE_TOOTH: 'Bluetooth',
    TESTING: 'Testing',
    NON_TESTING: 'Non Testing',
    COMPREHENSIVE: 'Comprehensive',
    NON_COMPREHENSIVE: 'Non-Comprehensive',




    MULTIGRAP: '多谱图对比',
    CONTINOUSTEST: '连续测试趋势图',
    NOVASOFT_V1: 'NovaSoft 1.0',
    NOVASOFT_V2: 'NovaSoft 2.0',
    V1_DOCUMENTS:'NovaSoft 1.0 Data',
    V2_DOCUMENTS:'NovaSoft 2.0 Data',
    V1_EXPORT_FOLDER: 'Export File',
    V2_EXPORT_FOLDER: 'export file',
    QUICK_TEST_FOLDER: 'Quick Test',
    CALI_TEST_FOLDER:'Calibrate',
    CUSTOMIZED_TEST_FOLDER: 'Customized Test',
    CONTINOUS_FILE_FOLDER: 'Schedule Data'
}